version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo Preparing frontend build
      - SRC_DIR="${CODEBUILD_SRC_DIR}"
      - FRONTEND_APP_DIR="${FRONTEND_APP_DIR:-app}"
      - FRONTEND_BUILD_OUTPUT_DIR="${FRONTEND_BUILD_OUTPUT_DIR:-dist}"
      - FRONTEND_BUILD_COMMAND="${FRONTEND_BUILD_COMMAND:-npm ci && npm run build}"
      - echo SRC_DIR=${SRC_DIR}
      - echo FRONTEND_APP_DIR=${FRONTEND_APP_DIR}
      - echo FRONTEND_BUILD_OUTPUT_DIR=${FRONTEND_BUILD_OUTPUT_DIR}
      - cd "${SRC_DIR}/${FRONTEND_APP_DIR}"
      - pwd

  build:
    commands:
      - echo Running frontend build
      - bash -lc "${FRONTEND_BUILD_COMMAND}"

  post_build:
    commands:
      - echo Syncing build output to S3
      - BUILD_OUTPUT_PATH="${SRC_DIR}/${FRONTEND_APP_DIR}/${FRONTEND_BUILD_OUTPUT_DIR}"
      - echo BUILD_OUTPUT_PATH=${BUILD_OUTPUT_PATH}
      - aws s3 sync "${BUILD_OUTPUT_PATH}" "s3://${SITE_BUCKET_NAME}" --delete
      - |
        if [ -n "${CLOUDFRONT_DISTRIBUTION_ID}" ] && [ "${CLOUDFRONT_DISTRIBUTION_ID}" != "none" ]; then
          echo Creating CloudFront invalidation
          aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths "/*"
        else
          echo CloudFront disabled
        fi

artifacts:
  files:
    - "**/*"
